### ISSUE TITLE
Not all settings shown in Admin Panel

### ISSUE THREAD

**Issue by adammhaile** [JN-Jones/MyBot#5]
I installed MyBot and Jones core on a 1.8.4 MyBB install but it only shows me a few options. In the admin settings listing it says (14 settings) but when I click through, all I see is this. What could I be doing wrong?

![image](https://cloud.githubusercontent.com/assets/957162/7150561/89fc168c-e2ea-11e4-80b6-badd8948ec07.png)

**Comment by JN-Jones** [comment]
The other settings depend on the shown ones and will be shown after you changed them, eg when the not should send a pm it'll show the pm settings.

**Comment by adammhaile** [comment]
The only thing it shows (as you can see from the picture) as being able to act on is new user registration and user birthday. But your plugin details says it can act on new threads... Nothing I change shows anything related to that. Do you have any documentation on usage for this?

**Comment by JN-Jones** [comment]
The main not settings are under users -> mybot

**Comment by adammhaile** [comment]
Ahh... now I found it. 
One last question though.... why I make a new rule for new posts and use {lastpost->subject} or any other lastpost var in the message it doesn't actually resolve to anything for new threads. Does it only work on posts, not threads?

**Comment by adammhaile** [comment]
Also, if I set the PM recipient to Specific User and then choose a user, it goes back to "Last Poster" when I save...
